import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <script
          crossOrigin
          src="https://unpkg.com/react@17/umd/react.production.min.js"
          async
        />
        <script
          crossOrigin
          src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"
          async
        />
        <script
          type="text/javascript"
          src="https://unpkg.com/@ant-design/plots@latest/dist/plots.min.js"
          async
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
